### ISSUE TITLE
some taar tests in python_mozetl seem to be intermittently failing

### ISSUE THREAD

**Issue by wlach** [mozilla/taar#114]
This started happening sometime in the last week or so, here's an example log:

https://circleci.com/gh/mozilla/python_mozetl/70#tests/containers/4

This may be related to a pyspark upgrade:

https://github.com/mozilla/python_mozetl/commit/0b97226f9fea26c177af0c91f33b23e70de67890

Note that upgrade actually just keeps the version we're using for testing in sync with the one we're using in production, so we really want to fix the root cause here rather than just revert versions.

For now I've filed a PR to temporarily disable the failing tests: 

https://github.com/mozilla/python_mozetl/pull/253

**Comment by crankycoder** [comment]
This was resolved by using the `.persist()` to manifest the dataframe.
