### ISSUE TITLE
Rework the hybrid recommendations

### ISSUE THREAD

**Issue by crankycoder** [mozilla/taar#125]
We are reworking the addon recommendations where some addons which need to be promoted regardless of whatever recommendations TAAR returns.

We'll need to sync with amo team to determine how we want this to be implemented.

Our requirements are that we must be able to definitively know the set of addons *displayed* to the user so that we can measure TAAR efficacy.

**Comment by crankycoder** [comment]
cc/ @muffinresearch

**Comment by mlopatka** [comment]
@crankycoder I think this issues is resolved. Can you  close it out?
