### ISSUE TITLE
Add API endpoint for validating that clientID has had the add-on installed

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/taar#151]
The idea behind this feature request is to provide a way for AMO to be able to validate abuse reports (and possibly ratings in the future) and make sure the reporter is someone who has used the add-on they are filing the report about at some point.

I think the basis on which addons-server would make the request would be to provide the following data (this is tentative and open to discussion):

* hashed clientId
* add-on guid
* ~~(optional) _Minimum install window (days)_  (if this is added up front this will make it easier for us to make adjustments to the validation queries we make without requiring an update).~~

To which we'd probably only initially need a boolean response (though we can confirm that).

This API would be called from addons-server and it **shouldn't be public**. For questions around operational details to make this server to server only, the best people to talk to would be @bqbn or @autrilla.

## Open questions

* Since we won't restrict validation to long install period, there is an edge-case around us making the call before the telemetry data is available. If that's the case we will defer the validation request for a period of time at the addons-server end.
* ~~We might want to set a minimum time that someone has installed the add-on. If we do this and the minimum install time is long enough that would make sure the data has made it to TAAR from the telemetry ping. However that would then rule out ever being able to verify shorter install to abuse report windows.~~

**Comment by crankycoder** [comment]
@muffinresearch ops has asked if we can run the TAAR service inside of a VPN instead of as a publicly reachable webservice.  I don't know have many details about the Fx67 modifications to the disco-pane.  Is there a contact for me to reach out to?

**Comment by muffinresearch** [comment]
@crankycoder is there a separate issue for that? Either way this shouldn't be a problem as long as addons-server can talk to TAAR, I don't think TAAR's API itself needs to be directly public, but addons-server's API which wraps TAAR would need to remain public.

**Comment by muffinresearch** [comment]
Talking to Jorge we can remove the idea that we'll track a specific window of time for verification. I'll strike the parts above that refer to that.

**Comment by crankycoder** [comment]
@muffinresearch  I'm going to follow up with the disco-pane changes I heard about tomorrow when I'm in the toronto office.  I'll update this bug tomorrow.
