### ISSUE TITLE
Add sufficient random chance (of surfacing a whitelisted addon) to increase recommendation rate of underrepressented GUIDs

### ISSUE THREAD

**Issue by mlopatka** [mozilla/taar#156]
We have reason to believe that only a subset of the total whitelisted addons are being surfaced as recommendations. This will be measured via the TAAR dashboard. It may be useful to provide a random component to increase recommendation diversity in cases where the confidence is already low for a subset of the addon recommendations.

**Comment by crankycoder** [comment]
Ideas: Collect distribution of weights for recommended addons after ensemble reweighting step.  

Determine a threshhold for low weight cut-off and substitude in a randomly selected GUID from whitelist.

**Comment by crankycoder** [comment]
Need to add logging that captures ensemble weights per recommended GUID.

**Comment by mlopatka** [comment]
I would propose that since the sorted recommendation list is already personalized on a per-client basis we can use a weighted sampling to introduce some variation while keeping the value of the personalized list.

This should function such that:

- Most individuals get highly confident recommendations most of the time
- Less confident recommendations are surfaced some of the time proportionate to how low their confidence is.

Maybe something like this could work right before the ensemble recommender returns weighted recommendations:

`
from numpy.random import choice

recommendations = ['guid1', 'guid2', 'guid3', 'guid4', 'guid5', 'guid6', 'guid7']
confidences =  [0.9, 0.01, 0.01, 0.01, 0.01, 0.01, 0.05]
k = 10 # Number of desired guids to recommend.

sample_numpy = choice(recommendations, k, p=confidences, replace=False)
# p is the probability density which here we use the confidence scores for.
#  replace=False means we don't have to de-duplicate

print(sample_numpy)
`

I have not bench-marked this code for realistic sized lists!

**Comment by mlopatka** [comment]
@crankycoder ^
