### ISSUE TITLE
Disco-TAAR should only select content from the approved Recommended list

### ISSUE THREAD

**Issue by devaneymoz** [mozilla/taar#157]
On Monday 15 July we officially launched the [Recommended Extensions](https://support.mozilla.org/en-US/kb/recommended-extensions-program) program. In accord with the guiding principles of this new, comprehensive editorial program, we (Mozilla) will only promote extensions that have been vetted through the Recommended review process. 

However Disco-TAAR is still making personalized recommendations based on an older, now-outdated subset of curated extensions located in the [Disco Pane admin](https://addons-internal.prod.mozaws.net/en-US/admin/models/discovery/discoveryitem/?p=0); this is also the same admin within which we are managing content in the Recommended Extensions program. 

As editorial manager of this program, if I need to mark content in the admin to become Recommended, I check a box labelled "Recommendable" (and the next version submission of that extension will go through a special review queue; if it passes, special privileges and labeling will be applied to it). It looks like this in the admin:

![image](https://user-images.githubusercontent.com/8496249/61336880-eef79e00-a7e7-11e9-897a-376cc6bda0ac.png)

We need to ensure TAAR is only making its personalized recs from the content in the admin when its Recommended status is marked as "Recommended".

Given the high traffic of the Disco Pane and our overt promise to users that anything promoted on Mozilla properties will meet the standards of the Recommended program, this should be considered a high priority bug. 

@mlopatka @crankycoder @muffinresearch @jvillalobos

**Comment by mlopatka** [comment]
Has anything changed regarding the **location** of the whitelist?

I expect that the whitelist we were pulling from previously is now replaced by the "recommended" list.
Can we verify this assumption @crankycoder @muffinresearch?

Assuming the availability of the recommended extension list, the models will update and non-recommended extensions will no longer appear in TAAR's output. 

Just to be extra sure and expedite the model refresh, can you kick off ETL jobs outside of schedule @crankycoder to clobber the stale models?

**Comment by muffinresearch** [comment]
@mlopatka I think you're currently grabbing data from `/api/v4/discovery/editorial/` this is everything not just add-ons part of the Recommended Extensions (RecEx) programme.

To fix that we'd need to add a filter to that endpoint and only export the recommended ones.

**Comment by muffinresearch** [comment]
I've filed https://github.com/mozilla/addons-server/issues/11851 please take a look and feedback there.

**Comment by crankycoder** [comment]
PR for this fix is at https://github.com/mozilla/python_mozetl/pull/334

**Comment by mlopatka** [comment]
Thanks @crankycoder [mozilla/python_mozetl#334](https://github.com/mozilla/python_mozetl/pull/334) closes this.
