### ISSUE TITLE
Change mention of https://addons.mozilla.org/api/v3/ in docs to /api/v4/

### ISSUE THREAD

**Issue by eviljeff** [mozilla/taar#189]
AMO api v3 is [deprecated](https://blog.mozilla.org/addons/2021/02/01/addons-mozilla-org-api-v3-deprecation/) - and was scheduled to be removed entirely at the end of 2021.  We're hoping to [finally remove](https://github.com/mozilla/addons-server/issues/18759#issuecomment-1033300945) it very soon.  

From a search on https://github.com/mozilla/ we've noted a reference to the /api/v3 endpoint in https://github.com/mozilla/taar/blob/main/docs/TAARLITE-README.md.  The top of the document says that Taar-lite is now merged into the main repo but I wasn't clear if the doc was still an active reference, or just left for historical purposes.  It should probably be updated either way.

**Comment by evgenyrp** [comment]
done
