### ISSUE TITLE
Add documentation on how to run tests

### ISSUE THREAD

**Issue by Dexterp37** [mozilla/taar#29]
We should really document the sequence of commands needed in order to run the tests locally, from installing the dependencies and running the tests.

**Comment by Dexterp37** [comment]
@maurodoglio any chance you could take this?

**Comment by crankycoder** [comment]
There is a test_requirements.txt file for pip now, and a `python setup.py test` directive which was added in ae33e453.

**Comment by Dexterp37** [comment]
Could you please add that to the README file, as not everyone knows about that.

**Comment by birdsarah** [comment]
Closing this now #29 is in.
