### ISSUE TITLE
encapsulate similarity metric in its own function

### ISSUE THREAD

**Issue by mlopatka** [mozilla/taar#36]
https://github.com/mozilla/taar/blob/b31b425c1111d372855cf730eec688f7b72463a1/taar/recommenders/similarity_recommender.py#L128

the similarity function used in this recommender should be encapsulated in a function that can be imported by the corresponsing [etl job](https://github.com/mozilla/python_mozetl/blob/master/mozetl/taar/taar_similarity.py) to ensure consistency between model generation and recommendations to the client.

**Comment by Dexterp37** [comment]
I don't think this is still valid: similarity_recommender.py was optimised to use Numpy/Scipy fast computation routines,. @mlopatka are we good to close this one?

**Comment by mlopatka** [comment]
Nope. This refers to something else. 

Currently the implementation using cdist is called with built in functions which are then combined into a univariate metric. This occurs separately for both the similarity_recommender in TAAR and the corresponding ETL job that generates donors and lr_curves.

However, cdist is also capable of accepting a  `callable` in the `metric` parameter. The encapsulation of a specific distance metric function to perform the distance computation inside the TAAR and then importing it in the ETL job would guarantee that the distance metric used for model generation and actual subsequent recommendations is the same distance metric. 

Currently this is not guaranteed, if a different metric were used it may even go unnoticed as no error would occur, but the quality of recommendations would presumably suffer.

**Comment by mlopatka** [comment]
fixed by PR #52
