### ISSUE TITLE
Refactor the caching system

### ISSUE THREAD

**Issue by maurodoglio** [mozilla/taar#47]
The main idea is to use a cache object passed to the RecommendationManager instead of reinventing the wheel. This object will be passed by taar api and it will likely be powered by the django cache system.

**Comment by crankycoder** [comment]
We should profile and measure any performance problems before implementing any possible solutions.

**Comment by Dexterp37** [comment]
This issue was filed after profiling was performed: is the data caching problem on the TAAR side solved?

**Comment by crankycoder** [comment]
I haven't seen the profile output - I'd like to see that run again.  Is there a stress test available?

**Comment by Dexterp37** [comment]
I don't have access to that specific profiling anymore, but it was performed as a consequence of mozilla/taar-api#14 . It was found that, in addition to the profile data fetching latency, seconds were spent downloading the data files for the modules on each request. For this reason, a naive caching system was put in place. The stress test was performed by ops before deployment.

Feel free to perform an in-depth profiling / fix this on the taar-api end. If you really want to close this issue, please file a new one to keep track of the problem.

**Comment by crankycoder** [comment]
I'm not expecting this to happen anymore with DynamoDB backing our requests.  All the models are now loaded as attributes of the recommenders.  I'm closing this bug for now.  If we see new performance problems with taar w/ensemble recommender, I'd rather get fresh metrics from newrelic and work on that.
