### ISSUE TITLE
Transmit locale from Discopane for very new clients

### ISSUE THREAD

**Issue by mlopatka** [mozilla/taar#50]
Discovery pane exposes some minimal client information in the form:
"https://discovery.addons.mozilla.org/%LOCALE%/firefox/discovery/pane/%VERSION%/%OS%/%COMPATIBILITY_MODE%"

The locale can be grabbed from this url and pass it to TAAR as an additional parameter along with the client_id so that TAAR can make locale-based recommendation even for users who are not yet present in the Hbase instance.

**Comment by mlopatka** [comment]
We agreed to submit a big to accomplish this functionality on the strict condition that an analysis was also performed to determine the root cause of TAAR failures for clients not found in H-Base.

**Comment by Dexterp37** [comment]
This is being fixed by #51 .
